### ISSUE TITLE
Generated Python code not installed if catkin_python_setup() was used.

### ISSUE THREAD

**Issue by hershwg** [ros/genmsg#10]
If catkin_python_setup() is used in a CMakeLists.txt file, genmsg's cmake code will avoid installing generated python message code.

The "tf" package does exactly this, because it has both message definitions and python code which needs to be installed.  I have worked around it with some hand-coded install() calls in the CMakeLists.txt file, but it surprises me that this does not just do the right thing automatically.

**Comment by dirk-thomas** [comment]
fixed in 6a87eb93a5e0bba6d58da1b9140f221c614c2f23
