### ISSUE TITLE
What is the version release policy in the community?

### ISSUE THREAD

**Issue by ysl-design** [ros/genmsg#101]
genmsg(0.5.16), gencpp(0.6.5), the most recent version of these code generation tools was two years ago. I would like to ask what the update strategy of the community is, whether the new version will not be released in the future.

**Comment by tfoote** [comment]
The code is generally quite stable but is heavily used. These packages are in maintenance for the duration of the [ROS Noetic Release](http://wiki.ros.org/noetic). If there are important bug fixes a release will be made. However, there is not expected to be any feature development. 

Releases are made when the maintainer has enough of a value to make a release. If there's a bug fix needed for your use case a release can be requested to increase the priority with the maintainer.

**Comment by ysl-design** [comment]
I got it. Thank you for your prompt response.
