### ISSUE TITLE
Hide transitive dependencies

### ISSUE THREAD

**Issue by dirk-thomas** [ros/genmsg#15]
If a package A generates messages which depend only on package B it should not need to know about B's dependencies to other message packages. Currently A has to specify all recursive message dependencies for `generate_messages(DEPENDENCIES ...)`.

All other parts in CMake (`find_package()`, `catkin_package()`) already provide that so `generate_messages()` should be the same.

**Comment by doudou** [comment]
I have some issue with that fix. I am using generate_messages outside of ROS the following way:

find_package(catkin)
find_package(base_msgs)
generate_messages(DEPENDENCIES base_msgs)

Where the messages I have in my package only use stuff from base_msgs. With that change, generate_messages complains that I should also explicitly find_package sensor_msgs and std_msgs (that base_msgs uses). Isn't that the opposite of what the bug report was expecting ? Am I missing something ?

**Comment by dirk-thomas** [comment]
I am pretty sure the fix works as expected.

In order to identify what is wrong in your scenario you need to provide more information. The snippet seems to be incomplete - you also need to `find_package(message_generation)` since you use the `generate_messages()` macro. Probably you should ask the question on answers.ros.org with more information and the complete code of your example (including stuff from base_msgs).
