### ISSUE TITLE
[genmsg] C++ messages use reserved names  (ros ticket #1298)

### ISSUE THREAD

**Issue by tfoote** [ros/genmsg#23]
Maybe this is incredibly OCD of me, but according to the C++ standard [17.4.3.1.2]: "Each name that contains a double underscore __ or begins with an underscore followed by an uppercase letter is reserved to the implementation for any use."

Not that I think it would ever happen in practice, but a C++ compiler would be within its rights to reject names like "__mutex" or "__getDataType".

trac data:
- Owner: **mquigley**
- Reporter: **mihelich**
- Reported at: **Wed Jun 24 19:27:21 2009**
- URL: https://code.ros.org/trac/ros/ticket/1298

**Comment by tfoote** [comment]
[mquigley] You're right, of course, but it's hard to say how big of a deal this is, and how much effort it's worth to correct it. It's handy to use the double-underscores in the hope that doing so will avoid unintended collisions with code using the ROS libraries. However, for the same reason, the compilers say we aren't supposed to use the double-underscore. Perhaps a middle ground is to prefix all of the auto-generated internal variables with __ros_. Hopefully we're less like to cause collisions with, e.g.,  __ros_mutex as opposed to __mutex. Thoughts?

**Comment by tfoote** [comment]
[mihelich] I guess the question is, when can collisions with user code occur? The only case I can think of is if a user declares a message with a field named {{{__mutex}}} (for example). So maybe we should just say that field names beginning with an underscore are invalid (reserved by ROS), and use internal names like {{{_mutex}}} (single underscore), or {{{_ros_mutex}}} if we want to be more explicit.

**Comment by tfoote** [comment]
[kwc] field names starting with underscores are illegal in ros

**Comment by dirk-thomas** [comment]
Closing this ticket since fields starting with an underscore are not supported (http://www.ros.org/wiki/msg).
