### ISSUE TITLE
[genmsg] msgs should have copy constructors  (ros ticket #3469)

### ISSUE THREAD

**Issue by tfoote** [ros/genmsg#25]
This is pretty simple to implement, so I did.  

NOTE: see also #2723

The attached msg_gen.py was modified from the Ubuntu 9.04 "latest" release.

The test file is not very formal, it just exercises the new API and prints to the console.

trac data:
- Owner: **dthomas**
- Reporter: **baxelrod**
- Reported at: **Tue Apr 26 10:32:20 2011**
- URL: https://code.ros.org/trac/ros/ticket/3469

**Comment by tfoote** [comment]
[baxelrod] FYI, I updated my attached files to work with the "unstable" release on 2011.05.25 to target the upcoming Electric Emys release.

**Comment by baxelrod-bdai** [comment]
@benaxelrod

**Comment by dirk-thomas** [comment]
This feature is already available for a long time - I think since the message generation has been rewritten for Fuerte. Therefore closing the issue.
