### ISSUE TITLE
calling generate_messages without declaring messages gives a bad error

### ISSUE THREAD

**Issue by wjwwood** [ros/genmsg#31]
This `CMakeLists.txt`:

https://github.com/allenh1/p2os/blob/eff7ff1beb99331ddcbd9bb05bf90aabead9bf38/p2os_teleop/CMakeLists.txt#L11

Results in this:

http://answers.ros.org/question/68278/jenkins-build-issues-file-install-cannot-find-obj-x86_64-linux-gnu/

It should probably assert that some messages are set to be generated, rather than failing when it tries to install the resulting files which obviously don't exist.

**Comment by dirk-thomas** [comment]
Indeed, it should not error out at all. The install rule must be wrapped in a condition if the folder actually exists.

**Comment by dirk-thomas** [comment]
And a warning would be nice if `generate_messages()` is invoked without any messages and services added before.
