### ISSUE TITLE
_has_header only resolves correctly if Header is the first type in the .msg file

### ISSUE THREAD

**Issue by csherstan** [ros/genmsg#55]
If a Header is included in a .msg file, but is not the first type, then the _has_header flag is set to False.

This is on line 257 of msgs.py.

```
 self.header_present = self.types[0] == HEADER_FULL_NAME and self.names[0] == 'header'
```

It is not clear to me why it is requiring that it be the first entry.

Either this should be corrected or the documentation at http://wiki.ros.org/msg should be updated to specify that Header must be first.

**Comment by dirk-thomas** [comment]
It actually is mentioned on the webpage that you referred to: http://wiki.ros.org/msg#Header

```
If the first field of your .msg is:
Header header
```

**Comment by csherstan** [comment]
Doh, sorry for wasting your time. Scanned it before posting, guess I wasn't
thorough enough.

Craig Sherstan

**Comment by csherstan** [comment]
Is there any reason to restrict it to the first field though?

Craig Sherstan

**Comment by dirk-thomas** [comment]
The header field has some special semantic. It is treated special in various places.

This "special" treatment should only be applied to this "special" field. If it would be not the first field it is questionable if the developer only wanted to use the data values of a header or if he actually wanted it to be treated "special". But the position restriction is mostly for legacy reasons. But that was the convention chosen in the beginning.

**Comment by dirk-thomas** [comment]
I will mark this as "wontfix" and close the ticket.
