### ISSUE TITLE
Add incremental mode

### ISSUE THREAD

**Issue by lochbrunner** [ros/genmsg#74]
Even in large projects with a lot of message definitions getting compiled, it would be nice if only messages get re-generated which have changed since the last generation.

Would it be possible to add this feature?

**Comment by dirk-thomas** [comment]
Changing message definitions as well as adding new message definitions is a rather rare event. So I am not sure if optimizing that is worth the effort and/or the extra complexity.

Please feel free to propose a pull request to improve this behavior is it is valuable for your use case.

**Comment by lochbrunner** [comment]
@dirk-thomas 
Changing is an rare event, I agree. In our use case: We using the *cmake* command `generate_messages` the messages get generated at each `cmake --build .`. Which consumes the most of the compile time.

**Comment by dirk-thomas** [comment]
That sounds like the culprit of the slowness. Maybe you can change your process to not require that effort during every make invocation.

**Comment by nlieb** [comment]
**edit**: never mind this comment! ccache won't cache the messages which makes sense.

Message generating also takes up the majority of time during our ccache'd rebuilds.

> Maybe you can change your process to not require that effort during every make invocation.

Do you have any pointers on how to do this? As far as I can tell, `generate_messages` is the only way to generate the messages, and its behaviour is not incremental.

**Comment by dirk-thomas** [comment]
> Do you have any pointers on how to do this? As far as I can tell, `generate_messages` is the only way to generate the messages, and its behaviour is not incremental.

As long as neither of the "inputs" changes a repeated build should not need to generate anything (assuming the output wasn't deleted in the meantime).
