### ISSUE TITLE
ROS course on edX error

### ISSUE THREAD

**Issue by JoshVM23** [ros/genmsg#96]
icy@aspire-a315-33:~/hrwros_ws/src/hrwros/hrwros_week1$ rosrun hrwros_week1 sensor_info_publisher.py
Traceback (most recent call last):
  File "/home/icy/hrwros_ws/src/hrwros/hrwros_week1/scripts/sensor_info_publisher.py", line 39, in <module>
    from hrwros_utilities.sim_sensor_data import distSensorData as getSensorData
ImportError: No module named hrwros_utilities.sim_sensor_data

THIS ERROR APPEARS WHEN I EXECUTE ROSRUN

**Comment by DeepMechatronics** [comment]
Basically, the hrwros_utilities package is probably missing in the directory.

Step 1:
Download [week1_contents_new2_fixed.zip](https://courses.edx.org/assets/courseware/v1/01b274edcf91f56f8cdd7c56ae05b139/asset-v1:DelftX+ROS1x+3T2018+type@asset+block/week1_contents_new2_fixed.zip) 

Reference:
https://courses.edx.org/courses/course-v1:DelftX+ROS1x+3T2018/f40348a2d8f648769ba3510c761c93a1/

Step 2:
Extract in relevant dir  like /src/hrwros

Step 3:
Catkin build

now try rosrun publisher

**Comment by tfoote** [comment]
This is not a problem with genmsg which is what this issue tracker should be used for. 

Please ask questions on http://answers.ros.org according to our support policy: http://wiki.ros.org/Support We try to keep the issue tracker reserved for bugs and feature developments.
